### PR TITLE
Issue#36: Added emitStrict flag

### LINKED ISSUE #36: Show warnings in js minify?
Is there a way to show error or warning if I am using a variable without first define it?

For example the following code:

```js
a = "hello";
```

vs

```js
let a = "hello";
```

I am using the following options:

```sh
options.strictModeInput = true
options.ignoreMinFiles = true
options.warningLevel = "DEFAULT"
options.originalFileNames = true
```
It won't give me any warnings if I just use a variable without first define it, and the result minified js does not work in browser, give me this error `Uncaught ReferenceError: a is not defined`.

if I change to 
```sh
options.warningLevel = "VERBOSE"
```

Then the build fails with many errors, won't even recognize jquery `$` sign.  Tried with `options.compilationLevel = "SIMPLE_OPTIMIZATIONS"`, same errors.

Thanks

### PR DESCRIPTION
**Pull request by 616slayer616**

### CODE REVIEW

File: src/main/kotlin/org/gradlewebtools/minify/minifier/js/JsMinifier.kt [hunk 1]
```diff
@@ -77,8 +78,8 @@ class JsMinifier(override var minifierOptions: JsMinifierOptions = JsMinifierOpt
         options.rewritePolyfills = minifierOptions.rewritePolyfills
         options.setOutputCharset(minifierOptions.charset)
         options.setChecksOnly(minifierOptions.checksOnly)
-        if (minifierOptions.browserFeaturesetYear != null) options.browserFeaturesetYear = minifierOptions
-                .browserFeaturesetYear
+        if (minifierOptions.browserFeaturesetYear != null) options.browserFeaturesetYear = minifierOptions.browserFeaturesetYear!!
```
Comment (timon-schelling) [inline src/main/kotlin/org/gradlewebtools/minify/minifier/js/JsMinifier.kt]: I don't understand what this change tries to do. Why "!!" ?

**Review by timon-schelling — CHANGES_REQUESTED** [review]

File: src/main/kotlin/org/gradlewebtools/minify/minifier/js/JsMinifier.kt (hunk 1 above)
Comment (616slayer616) [reply src/main/kotlin/org/gradlewebtools/minify/minifier/js/JsMinifier.kt]: I reverted it.
At the time the compiler told me it is neccessary.

**Review by timon-schelling — APPROVED** [review]
👏😊
